import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { MenuProvider } from "@/providers/menu";
import ToastProvider from "@/providers/toastProvider";
config.autoAddCss = false; // Prevent Font Awesome from adding its own CSS

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-screen antialiased bg-taupe-100 dark:bg-taupe-900 scroll-smooth`}
        >
            <body className="flex flex-col font-sans text-taupe-600 dark:text-taupe-200 bg-taupe-100 dark:bg-taupe-900">
                <ToastProvider>
                    <MenuProvider>{children}</MenuProvider>
                </ToastProvider>
            </body>
        </html>
    );
}
